trigger:
  branches:
    include:
      - master

pool:
  name: 'Default'  # This tells Azure to use the 'Default' pool where your 'AMAN' agent lives

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install
    displayName: 'Install Playwright browsers'

  - script: npx playwright test
    displayName: 'Run Playwright tests'