trigger:
  branches:
    include:
      - master

stages:
  - stage: First_Stage
    displayName: First Stage
    jobs:
      - job: Job_One
        displayName: Job One
        steps:
          - script: echo "Hey Braah"